name: Validar HTML y CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependencias
        run: npm install html-validator-cli csslint

      - name: Validar HTML con HTML Validator
        run: npx html-validator-cli --file=index.html --format=text

      - name: Validar CSS con CSS Lint
        run: npx csslint styles.css || true